spring.application.name=gestion
server.port=8080
python.service.base-url=http://localhost:5000
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false
